Exit with compiled error

diff --git a/clam b/clam
--- a/clam
+++ b/clam
@@ -87,7 +87,9 @@ case "${1}" in
         "$0" compile || exit $?
         echo -e "\n===Running ${PWD##*/}===\n"
         time ./build/"${PWD##*/}"
-        echo "Exited with error code: $?"
+        err=$?
+        echo "Exited with error code: $err"
+        exit "$err"
         ;;
     *)
         help_print
